name: Run Shell Script

on:
  workflow_dispatch:  # This allows the workflow to be triggered manually

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Change permissions for script
      run: chmod +x ./script.sh 

    - name: Run shell script
      run: ./script.sh